"use client"; 
/*import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}*/



import React from 'react';
import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: '求人検索アプリ',
  description: 'Next.jsとSupabaseを使用した求人検索アプリケーション',
};

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="ja">
      <body className="min-h-screen bg-gray-100">
        <header className="bg-gray-800 text-white p-4">
          <div className="max-w-7xl mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">求人検索アプリ</h1>
            <nav className="flex space-x-4">
              <Link href="/" className="hover:underline">
                求人検索
              </Link>
              <Link href="/post" className="hover:underline">
                求人投稿
              </Link>
            </nav>
          </div>
        </header>

        <main className="max-w-7xl mx-auto py-8 px-4">
          {children}
        </main>
      </body>
    </html>
  );
};

export default Layout;
